/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SR;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.parser.TokenType;

/**
 *
 * @author ASUS
 */
public class Kontak extends javax.swing.JFrame {
    private Connection con = new Koneksi().connect();
    private Statement stm;
            
    /**
     * Creates new form Kontak
     */
    public Kontak() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        tampil();
        awal();
    }
    private void tampil(){
        String bagian = info.getText();
        if (bagian=="Divisi IT") {
            bagian = "IT";
        }else if(bagian=="Divisi Procurement"){
            bagian = "Procurement";
        }else{
            bagian = "Facility";
        }
        DefaultTableModel tab = new DefaultTableModel();
        tab.addColumn("ID");
        tab.addColumn("Nama");
        tab.addColumn("Alamat Email");
        tab.addColumn("Ext");
        tab.addColumn("Divisi");
        try {
            stm=(Statement)con.createStatement();
            String sql ="Select * from kontak WHERE bagian ='"+bagian+"'";
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                Object [] o = new Object[5];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("email");
                o[3] = rs.getString("ext");
                o[4] = rs.getString("bagian");
                tab.addRow(o);
            }
            tabel.setModel(tab);
            stm.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    protected void awal(){
      btnedit.setEnabled(false);
      btntambah.setEnabled(true);
      btnsimpan.setEnabled(false);
      btnhapus.setEnabled(false);
      btnbatal.setEnabled(false);
      nama.setText("");
      id.setText("");
      email.setText("");
      ext.setText("");
      id.setEnabled(false);
      nama.setEnabled(false);
      ext.setEnabled(false);
      email.setEnabled(false);
    }
    private void no_id(){
        try {
            stm=(Statement)con.createStatement();
             String sql = "SELECT * FROM kontak ORDER by id desc";
             ResultSet rs = stm.executeQuery(sql);
             if (rs.next()) {
               String nmid = rs.getString("id");
               String nid = ""+ (Integer.parseInt(nmid) + 1);
               id.setText(""+nid);
             }
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btntambah = new javax.swing.JToggleButton();
        btnhapus = new javax.swing.JToggleButton();
        btnedit = new javax.swing.JToggleButton();
        btnsimpan = new javax.swing.JToggleButton();
        btnbatal = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ext = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(201, 193, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(79, 59, 56));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        info.setForeground(new java.awt.Color(201, 193, 176));
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 640, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 193, 176));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data Info");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 80));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 570, 150));

        btntambah.setBackground(new java.awt.Color(79, 59, 56));
        btntambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btntambah.setForeground(new java.awt.Color(201, 193, 176));
        btntambah.setText("Tambah Data");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 93, 130, 30));

        btnhapus.setBackground(new java.awt.Color(79, 59, 56));
        btnhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(201, 193, 176));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 100, 30));

        btnedit.setBackground(new java.awt.Color(79, 59, 56));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnedit.setForeground(new java.awt.Color(201, 193, 176));
        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 100, 30));

        btnsimpan.setBackground(new java.awt.Color(79, 59, 56));
        btnsimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(201, 193, 176));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 100, 30));

        btnbatal.setBackground(new java.awt.Color(79, 59, 56));
        btnbatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnbatal.setForeground(new java.awt.Color(201, 193, 176));
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 193, 176));
        jLabel2.setText("Ext");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 193, 176));
        jLabel3.setText("Id");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 70, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(201, 193, 176));
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 70, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(201, 193, 176));
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 70, 30));
        jPanel1.add(ext, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 170, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 60, 30));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 140, 30));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 170, 30));

        jPanel3.setBackground(new java.awt.Color(79, 59, 56));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 580, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int bar = tabel.getSelectedRow();
        String a = tabel.getValueAt(bar, 0).toString();
        String b = tabel.getValueAt(bar, 1).toString();
        String c = tabel.getValueAt(bar, 2).toString();
        String d = tabel.getValueAt(bar, 3).toString();
        
        btnhapus.setEnabled(true);
        btnedit.setEnabled(true);
        btnbatal.setEnabled(true);
        btntambah.setEnabled(false);
        id.setEnabled(false);
        nama.setEnabled(true);
        ext.setEnabled(true);
        email.setEnabled(true);
        nama.setText(b);
        id.setText(a);
        email.setText(c);
        ext.setText(d);
        
    }//GEN-LAST:event_tabelMouseClicked

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        awal();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            stm=(Statement)con.createStatement();
            String sql="UPDATE kontak SET nama='"+nama.getText()+"',email='"+email.getText()+"',ext='"+ext.getText()+"' WHERE id='"+id.getText()+"'";
            stm.executeUpdate(sql);
            stm.close();
            tampil();
            awal();
            JOptionPane.showMessageDialog(null, "Edit Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Data Akan Dihapus, Teruskan Hapus ?", "Penghapusan Data", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_OPTION){
        try {
            stm=(Statement)con.createStatement();
            String sql ="DELETE FROM kontak WHERE id= '"+id.getText()+"'";
            stm.executeUpdate(sql);
            stm.close();
            JOptionPane.showMessageDialog(null, "Berhasil Di hapus");
            tampil();
            awal();
         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
         }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        btnsimpan.setEnabled(true);
        id.setEnabled(true);
        id.setEditable(false);
        nama.setEnabled(true);
        ext.setEnabled(true);
        email.setEnabled(true);
        btnbatal.setEnabled(true);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        no_id();
        
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String bagian = info.getText();
        if (bagian=="Divisi IT") {
            bagian = "IT";
        }else if(bagian=="Divisi Procurement"){
            bagian = "Procurement";
        }else{
            bagian = "Facility";
        }
        try {
            stm=(Statement)con.createStatement();
            String sql="INSERT INTO kontak VALUES('"+id.getText()+"','"+nama.getText()+"','"+email.getText()+"','"+ext.getText()+"','"+bagian+"')";
            stm.executeUpdate(sql);
            stm.close();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Tambahkan");
            tampil();
            awal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kontak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kontak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnbatal;
    private javax.swing.JToggleButton btnedit;
    private javax.swing.JToggleButton btnhapus;
    private javax.swing.JToggleButton btnsimpan;
    private javax.swing.JToggleButton btntambah;
    private javax.swing.JTextField email;
    private javax.swing.JTextField ext;
    private javax.swing.JTextField id;
    public static final javax.swing.JLabel info = new javax.swing.JLabel();
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nama;
    public static final javax.swing.JTable tabel = new javax.swing.JTable();
    // End of variables declaration//GEN-END:variables
}
