/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SR;

import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class ProsesSR extends javax.swing.JFrame {
    java.util.Date tanggal = new java.util.Date();
    private final SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
    private final String tgl = smpdtfmt.format(tanggal);
  
    /**
     * Creates new form ProsesSR
     */
    public ProsesSR() {
        initComponents();
        setLocationRelativeTo(this);
        buttonGroup1.add(rbtnAsset);
        buttonGroup1.add(rbtnBiaya); 
        buttonGroup1.add(rbtntolak);
        txtTgl.setText(tgl);
        awal();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("SR Proses");
    }
    private Connection Con = new Koneksi().connect();
    private Statement stm;
    
   
    private void proses(){
        String tgl = txtTgl.getText();
        String no = txtNoSR.getText();
        String io = txtIo.getText();
        String st = txtsite.getText();
        
        String pilih = "";
        if (rbtnAsset.isSelected()) {
            pilih = rbtnAsset.getText();
        } else {
            pilih = rbtnBiaya.getText();
        }
        String penawaran = txtHarga.getText();
        String vendor = txtVendor.getText();
        String pic = String.valueOf(cmbPIC.getSelectedItem());
        try {
            stm = (Statement) Con.createStatement();
            String sql = "INSERT INTO dist_sr(tgl,nomor_sr,s_location,internal_order,harga,vendor,jenis_sr,pic,keterangan)"
                    + " VALUE ('"+tgl+"','"+no+"','"+st+"','"+io+"','"+penawaran+"','"+vendor+"','"+pilih+"','"+pic+"','"+ket.getText()+"')";
            int executeUpdate = stm.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Proses Berhasil");
            awal();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            
            String dst ="Di teruskan ke "+pic;
            try {
                String sq ="UPDATE srbaru SET status = '"+dst+"' WHERE nomor_sr LIKE '"+no+"'";
                String sql = "UPDATE budget_toko SET saldo =(saldo-'"+penawaran+"') WHERE internal_order = '"+io+"'";
                stm=(Statement) Con.createStatement();
                awal();
                int execute =stm.executeUpdate(sql);
                int update = stm.executeUpdate(sq);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }
    private void awal(){
        btnproses.setEnabled(false);
        rbtnAsset.setEnabled(false);
        rbtnBiaya.setEnabled(false);
        //cetak.setEnabled(false);
        txtVendor.setText("");
        txtIo.setEditable(false);
        txtsite.setEditable(false);
        buttonGroup1.clearSelection();
        txtHarga.setText("");
        txtsite.setText("");
        txtIo.setText("");
        ket.setText("");
        cmbPIC.setSelectedItem("- PIC Division -");
    }
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
   }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnproses = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        ket = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbPIC = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableproses = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtIo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtsite = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtVendor = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNoSR = new javax.swing.JTextField();
        rbtnAsset = new javax.swing.JRadioButton();
        rbtnBiaya = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        txtTgl = new javax.swing.JLabel();
        rbtntolak = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(201, 193, 176));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(229, 225, 216));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(229, 225, 216));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proses SR");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 40));

        jPanel2.setBackground(new java.awt.Color(79, 59, 56));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(229, 225, 216));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Vendor");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 20));

        jLabel8.setText("Site Location");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 20));

        btnproses.setBackground(new java.awt.Color(156, 111, 105));
        btnproses.setForeground(new java.awt.Color(79, 59, 56));
        btnproses.setText("Proses");
        btnproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesActionPerformed(evt);
            }
        });
        jPanel3.add(btnproses, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 70, 30));

        cetak.setBackground(new java.awt.Color(156, 111, 105));
        cetak.setForeground(new java.awt.Color(79, 59, 56));
        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel3.add(cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 70, 30));
        jPanel3.add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, -1));

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });
        jPanel3.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 130, -1));

        jLabel9.setText("Alasan Ditolak");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 130, 20));

        cmbPIC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- PIC Division -", "Procurement", "Facility", "IT" }));
        jPanel3.add(cmbPIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, 20));

        tableproses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableproses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableprosesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableproses);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 90));

        jLabel10.setText("Harga Penawaran");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 20));
        jPanel3.add(txtIo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, -1));

        jLabel11.setText("Internal Order");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 110, 20));
        jPanel3.add(txtsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 80, -1));

        jLabel12.setText("Buyer PIC");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 20));
        jPanel3.add(txtVendor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 210, -1));

        btncancel.setBackground(new java.awt.Color(156, 111, 105));
        btncancel.setForeground(new java.awt.Color(79, 59, 56));
        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel3.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 70, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 410));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 590, 430));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("No SR    :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 70, 30));

        txtNoSR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNoSR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoSRActionPerformed(evt);
            }
        });
        jPanel1.add(txtNoSR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 30));

        rbtnAsset.setText("Asset");
        rbtnAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAssetActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnAsset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, 30));

        rbtnBiaya.setText("Biaya");
        rbtnBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBiayaActionPerformed(evt);
            }
        });
        jPanel1.add(rbtnBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 30));

        jPanel4.setBackground(new java.awt.Color(79, 59, 56));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 100));

        txtTgl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTgl.setForeground(new java.awt.Color(79, 59, 56));
        txtTgl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTgl.setText("jLabel1");
        jPanel1.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 120, 30));

        rbtntolak.setText("Ditolak");
        rbtntolak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtntolakActionPerformed(evt);
            }
        });
        jPanel1.add(rbtntolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
      int opsi = JOptionPane.showConfirmDialog(null, "Cetak Distribusi SR ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (opsi == JOptionPane.YES_OPTION){
                InputStream streamLaporan = getClass().getResourceAsStream("/LAPORAN/dist_sr.jasper");
                try {
                    
                    stm=(Statement) Con.createStatement();
                    HashMap parameter = new HashMap();
                    parameter.put("kode", tgl);
                    JasperPrint jprint = JasperFillManager.fillReport(streamLaporan, parameter, Con);
                    JasperViewer.viewReport(jprint, false);
                    
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }
            }
    }//GEN-LAST:event_cetakActionPerformed

    private void rbtnAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAssetActionPerformed
        // TODO add your handling code here:
        ket.setEnabled(true);
        txtHarga.setEnabled(true);
        txtsite.setEnabled(true);
        txtIo.setEnabled(true);
        btnproses.setEnabled(true);
    }//GEN-LAST:event_rbtnAssetActionPerformed

    private void rbtnBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBiayaActionPerformed
        // TODO add your handling code here:
        //ket.setEnabled(false);
        txtHarga.setEnabled(false);
        txtHarga.setText("0");
        btnproses.setEnabled(true);
    }//GEN-LAST:event_rbtnBiayaActionPerformed

    private void btnprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesActionPerformed
        // TODO add your handling code here:
        String keterangan = ket.getText();
        if(rbtntolak.isSelected()){
            String pic ="-";
            String jenis = rbtntolak.getText();
            String harga = txtHarga.getText();
            String vendor = "-";
            try {
                stm =Con.createStatement();
                String sql="INSERT INTO dist_sr(tgl,nomor_sr,s_location,internal_order,harga,vendor,jenis_sr,pic,keterangan) VALUES('"+txtTgl.getText()+"','"+txtNoSR.getText()+"','"+txtsite.getText()+"','"+txtIo.getText()+"','"+harga+"','"+vendor+"','"+jenis+"','"+pic+"','"+keterangan+"')";
                stm.executeUpdate(sql);
                awal();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }finally{
            
            String dst ="Ditolak Teritory Head ";
            try {
                stm = Con.createStatement();
                String sq ="UPDATE srbaru SET status = '"+dst+"' WHERE nomor_sr LIKE '"+txtNoSR.getText()+"'";
                stm.executeUpdate(sq);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        else if(cmbPIC.getSelectedItem().equals("- PIC Division -")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "Info", JOptionPane.INFORMATION_MESSAGE);
        }else{
        proses();
        txtNoSR.setText("");
        awal();
        }
    }//GEN-LAST:event_btnprosesActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_txtHargaKeyTyped

    private void tableprosesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableprosesMouseClicked
        // TODO add your handling code here:
        int baris = tableproses.rowAtPoint(evt.getPoint());
        String io = tableproses.getValueAt(baris, 1).toString();
        String site = tableproses.getValueAt(baris, 4).toString();
        txtIo.setText(io);
        txtsite.setText(site);
    }//GEN-LAST:event_tableprosesMouseClicked

    private void txtNoSRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoSRActionPerformed
        // TODO add your handling code here:
        
        {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("Nama Toko");
        tabel.addColumn("Internal Order");
        tabel.addColumn("Jenis");
        tabel.addColumn("Deskripsi");
        tabel.addColumn("Site Location");
       String nomor = txtNoSR.getText();
       try{
       stm = (Statement) Con.createStatement();
       String sql =  "SELECT nama_toko,internal_order,jenis_permintaan,deskripsi,lokasi.s_location "
               + "FROM lokasi,srbaru WHERE srbaru.s_location = lokasi.s_location AND srbaru.nomor_sr LIKE  '"+nomor+"'";
       ResultSet rs = stm.executeQuery(sql);
            while (rs.next()){
                Object[] o = new Object[5];
                o[0] = rs.getString("nama_toko");
                o[1] = rs.getString("internal_order");
                o[2] = rs.getString("jenis_permintaan");
                o[3] = rs.getString("deskripsi");
                o[4] = rs.getString("s_location");
                cmbPIC.setEnabled(true);
                tabel.addRow(o);
                rbtnAsset.setEnabled(true);
                rbtnBiaya.setEnabled(true);
                cetak.setEnabled(true);
                btnproses.setEnabled(true);
            }
            tableproses.setModel(tabel);
            stm.close();
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }   
    }
    }//GEN-LAST:event_txtNoSRActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelActionPerformed

    private void rbtntolakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtntolakActionPerformed
        // TODO add your handling code here:
        ket.setEnabled(true);
        txtIo.setEnabled(false);
        cmbPIC.setEnabled(false);
        txtHarga.setEnabled(false);
        txtHarga.setText("0");
        btnproses.setEnabled(true);
        
    }//GEN-LAST:event_rbtntolakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProsesSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProsesSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProsesSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProsesSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProsesSR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnproses;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetak;
    private javax.swing.JComboBox<String> cmbPIC;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ket;
    private javax.swing.JRadioButton rbtnAsset;
    private javax.swing.JRadioButton rbtnBiaya;
    private javax.swing.JRadioButton rbtntolak;
    private javax.swing.JTable tableproses;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIo;
    private javax.swing.JTextField txtNoSR;
    private javax.swing.JLabel txtTgl;
    private javax.swing.JTextField txtVendor;
    private javax.swing.JTextField txtsite;
    // End of variables declaration//GEN-END:variables
}
